export default {
  index: 'Overview',
  editor: 'Config Editor',
  features: 'Feature Toggles',
  branding: 'Branding & Backup',
  localisation: 'Localisation',
  convars: 'Server Convars',
  main: 'Main Config (config.lua)',
  discord: 'Discord & Duty',
  permissions: 'Permissions & ACE',
  notifications: 'Notifications',
  phone: 'Phone',
  'cad-terminals': 'CAD Terminals & Routing',
  items: 'Inventory Items',
  'law-enforcement': 'Penal Code & Evidence',
  'records-personnel': 'Records, Personnel & Supervisor',
  supervisor: 'Supervisor Panel',
  hud: 'HUD & Player List',
  'gameplay-modules': 'Gameplay & Misc Modules',
  civilian: 'Civilian & Emotes',
  security: 'Anticheat & Security',
  profile: 'Profile & Achievements',
  world: 'World, Blips & Props',
}
