'use client'

import './config-wizard.css'
import { useMemo, useState } from 'react'
import { SECTIONS, CONVAR_TEMPLATE } from '../lib/configSchema.js'

// ── Lua value formatting ─────────────────────────────────────────────────────
function luaValue(field, v) {
  if (field.type === 'bool') return v ? 'true' : 'false'
  if (field.type === 'number') {
    const n = Number(v)
    return Number.isFinite(n) ? String(n) : '0'
  }
  // text / select → quoted string, escape backslash + quote
  return '"' + String(v ?? '').replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"'
}

// Build the assembled config text, grouped by target file. `onlyChanged` limits the
// output to values that differ from the default.
function assemble(values, onlyChanged) {
  const byFile = new Map()
  for (const sec of SECTIONS) {
    for (const f of sec.fields) {
      const v = values[f.id]
      const isDefault = String(v) === String(f.default)
      if (onlyChanged && isDefault) continue
      if (!byFile.has(f.file)) byFile.set(f.file, [])
      byFile.get(f.file).push(`${f.path} = ${luaValue(f, v)}`)
    }
  }

  const blocks = []
  blocks.push(
    '-- ════════════════════════════════════════════════════════════════════\n' +
    '--  LACORE config — generated by the Config Editor\n' +
    '--  Paste each block at the END of the named file (it overrides the default).\n' +
    '-- ════════════════════════════════════════════════════════════════════'
  )
  // server.cfg secrets template first
  blocks.push(`# ▼▼▼  server.cfg  ▼▼▼\n${CONVAR_TEMPLATE}`)
  for (const [file, lines] of byFile) {
    if (lines.length === 0) continue
    blocks.push(`-- ▼▼▼  ${file}  ▼▼▼\n${lines.join('\n')}`)
  }
  return blocks.join('\n\n')
}

function download(text) {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = 'lacore-config.txt'
  document.body.appendChild(a)
  a.click()
  a.remove()
  setTimeout(() => URL.revokeObjectURL(url), 1000)
}

// ── Field control ────────────────────────────────────────────────────────────
function Field({ field, value, onChange }) {
  return (
    <div className="cw-field">
      <div className="cw-field-main">
        <div className="cw-field-label">{field.label}</div>
        <div className="cw-field-help">{field.help}</div>
        <code className="cw-field-path">{field.path}</code>
      </div>
      <div className="cw-field-ctl">
        {field.type === 'bool' && (
          <button
            type="button"
            className={'cw-toggle' + (value ? ' on' : '')}
            aria-pressed={value}
            onClick={() => onChange(!value)}
          >
            <span className="cw-knob" />
            <span className="cw-toggle-txt">{value ? 'ON' : 'OFF'}</span>
          </button>
        )}
        {field.type === 'number' && (
          <input className="cw-input" type="number" value={value}
            onChange={(e) => onChange(e.target.value)} />
        )}
        {field.type === 'text' && (
          <input className="cw-input" type="text" value={value}
            onChange={(e) => onChange(e.target.value)} />
        )}
        {field.type === 'select' && (
          <select className="cw-input" value={value} onChange={(e) => onChange(e.target.value)}>
            {field.options.map(([val, lbl]) => <option key={val} value={val}>{lbl}</option>)}
          </select>
        )}
      </div>
    </div>
  )
}

// ── Wizard ───────────────────────────────────────────────────────────────────
export function ConfigWizard() {
  const initial = useMemo(() => {
    const v = {}
    for (const sec of SECTIONS) for (const f of sec.fields) v[f.id] = f.default
    return v
  }, [])

  const [values, setValues] = useState(initial)
  const [step, setStep] = useState(0)
  const [onlyChanged, setOnlyChanged] = useState(false)
  const [copied, setCopied] = useState(false)

  const total = SECTIONS.length + 1 // +1 review step
  const isReview = step === SECTIONS.length
  const sec = SECTIONS[step]

  const output = useMemo(() => assemble(values, onlyChanged), [values, onlyChanged])
  const changedCount = useMemo(() => {
    let n = 0
    for (const s of SECTIONS) for (const f of s.fields) if (String(values[f.id]) !== String(f.default)) n++
    return n
  }, [values])

  const set = (id, val) => setValues((prev) => ({ ...prev, [id]: val }))
  const go = (i) => setStep(Math.max(0, Math.min(total - 1, i)))

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(output)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch { /* clipboard blocked — download still works */ }
  }

  return (
    <div className="cw">
      {/* Progress rail */}
      <div className="cw-rail">
        {SECTIONS.map((s, i) => (
          <button
            key={s.id}
            type="button"
            className={'cw-step' + (i === step ? ' active' : '') + (i < step ? ' done' : '')}
            onClick={() => go(i)}
            title={s.title}
          >
            <span className="cw-step-ico">{s.icon}</span>
            <span className="cw-step-txt">{s.title}</span>
          </button>
        ))}
        <button
          type="button"
          className={'cw-step' + (isReview ? ' active' : '')}
          onClick={() => go(SECTIONS.length)}
          title="Review & download"
        >
          <span className="cw-step-ico">✅</span>
          <span className="cw-step-txt">Review</span>
        </button>
      </div>

      <div className="cw-body">
        {!isReview && (
          <>
            <div className="cw-head">
              <h3>{sec.icon} {sec.title}</h3>
              <span className="cw-file">{sec.file}</span>
            </div>
            <p className="cw-intro">{sec.intro}</p>
            <div className="cw-fields">
              {sec.fields.map((f) => (
                <Field key={f.id} field={f} value={values[f.id]} onChange={(v) => set(f.id, v)} />
              ))}
            </div>
          </>
        )}

        {isReview && (
          <>
            <div className="cw-head">
              <h3>✅ Review &amp; download</h3>
              <span className="cw-file">{changedCount} setting(s) changed from default</span>
            </div>
            <p className="cw-intro">
              Below is your assembled config. Paste each block at the <strong>end</strong> of the file it
              names — a re-assignment there cleanly overrides the default. Fill in the real secret values
              in <code>server.cfg</code> locally. Then restart the resource.
            </p>
            <label className="cw-check">
              <input type="checkbox" checked={onlyChanged} onChange={(e) => setOnlyChanged(e.target.checked)} />
              Only include settings I changed
            </label>
            <div className="cw-actions">
              <button type="button" className="cw-btn primary" onClick={() => download(output)}>⬇ Download lacore-config.txt</button>
              <button type="button" className="cw-btn" onClick={copy}>{copied ? '✓ Copied' : '📋 Copy'}</button>
            </div>
            <pre className="cw-out"><code>{output}</code></pre>
          </>
        )}
      </div>

      {/* Nav */}
      <div className="cw-nav">
        <button type="button" className="cw-btn" disabled={step === 0} onClick={() => go(step - 1)}>← Back</button>
        <span className="cw-count">Step {step + 1} / {total}</span>
        <button type="button" className="cw-btn primary" disabled={step === total - 1} onClick={() => go(step + 1)}>Next →</button>
      </div>
    </div>
  )
}
