// Roadmap phases, rendered as a horizontal timeline by components/Roadmap.jsx.
// Keep this the single source of truth — edit here, not in the MDX.

export const phases = [
  {
    when: 'Shipped',
    status: 'Shipped',
    icon: '✅',
    accent: '#22c55e',
    title: 'The Foundation',
    tag: 'v3.1 – v3.2',
    items: [
      '5 MDTs — LAPD · LASD · Agency · EMS/Fire · 9100-T',
      'Dispatch console + zone / district editor',
      'CCTV suite — scanner, field cams, map',
      'BOLOs · charges · citations · penal code',
      'Evidence & reports · multi-char profiles',
      'Security stack + ESX / QB / QBox bridge',
      'Civilian base — emotes, ID, props, orgs, turf',
      'External web dispatcher',
    ],
  },
  {
    when: 'Shipped',
    status: 'Shipped',
    icon: '✅',
    accent: '#22c55e',
    title: 'Communications',
    tag: 'v3.2.0',
    items: [
      'Full NUI phone — calls, SMS, camera, 7+ apps',
      'Structured 911 / 311 → dispatch (with voice)',
      'Contacts, messaging & RP tools',
      'Corrections / jail · impound / tow · air unit · K9',
    ],
  },
  {
    when: 'Shipped',
    status: 'Shipped',
    icon: '✅',
    accent: '#22c55e',
    title: 'Depth & Polish',
    tag: 'v3.3 – v3.4',
    items: [
      'Pennsylvania CAD (paid add-on, 6th terminal)',
      'Replay & Director’s Cut studio',
      'Anticheat observe mode — on by default, reviewable',
      'In-car CAD screen — per-seat, legible, clickable',
      'Speech-to-text radio log (experimental)',
      'New address system (NADS) · fingerprints',
      'Dashboards — config editor, model library, add-ons',
      'Supervisor panel gated by ACE / Discord role',
    ],
  },
  {
    when: 'Next',
    status: 'Planned',
    icon: '🧍',
    accent: '#a855f7',
    title: 'Civilian Depth II',
    items: [
      'Org / gang expansion — territory, ranks, MOTD',
      'Turf balancing & anti-farm tuning',
      'Civ interactions — show ID, hand over',
      'More props & tools',
    ],
  },
  {
    when: 'Later',
    status: 'Planned',
    icon: '🚔',
    accent: '#ef4444',
    title: 'LEO Depth II',
    items: [
      'Warrant workflow (request → approval)',
      'Court / DA integration',
      'DNA forensics (fingerprints already shipped)',
      'Automatic ALPR on cameras → BOLO hit',
    ],
  },
  {
    when: 'Vision',
    status: 'Exploring',
    icon: '🚀',
    accent: '#ec4899',
    title: 'The Vision',
    items: [
      'Web records / DA portal',
      'Deeper framework interop',
      'More languages · performance budget',
      'LACORE for Roblox',
    ],
  },
]
