// Central place for share-preview (Open Graph / Twitter Card) metadata.
//
// When a docs link is pasted into Discord, WhatsApp, Slack, X, iMessage, … the
// scraper reads these <meta> tags to render a thumbnail card. The image MUST be
// PNG/JPEG at an ABSOLUTE URL — social scrapers do not render SVG and do not
// resolve base-path-relative paths — so everything here is emitted absolute.
//
// The release cards under /public/changelog/*.png and the default /public/og/
// card are generated by scripts/gen-changelog.mjs (rasterised from the same SVG
// template the changelog pages show as a banner).

// Origin the site is served from. GitHub Pages project site by default; override
// with NEXT_PUBLIC_SITE_URL if a custom domain is ever added.
export const SITE = process.env.NEXT_PUBLIC_SITE_URL || 'https://tabysi.github.io'

// Repo base path ('/lacore-docs' in the deployed Pages build, '' locally). Set
// by the deploy workflow via NEXT_PUBLIC_BASE_PATH — same source next.config uses.
export const BASE = process.env.NEXT_PUBLIC_BASE_PATH || ''

// A root-relative public path → absolute URL that includes the base path.
export const abs = (p) => `${SITE}${BASE}${p.startsWith('/') ? p : '/' + p}`

export const SITE_NAME = 'LACORE Documentation'
export const DEFAULT_DESCRIPTION =
  'Official documentation for LACORE — the all-in-one configurable roleplay core for FiveM, by @tabysi.'

// The site-wide fallback card, shown for any page without its own image.
export const DEFAULT_OG_IMAGE = abs('/og/default.png')

// Build the openGraph + twitter blocks. Next merges metadata shallowly and does
// NOT deep-merge openGraph/twitter, so every page that sets them must pass the
// full block — this returns exactly that.
export function share({ title, description = DEFAULT_DESCRIPTION, image = DEFAULT_OG_IMAGE, path = '' } = {}) {
  const url = path ? abs(path) : `${SITE}${BASE}/`
  const heading = title ? `${title} — LACORE` : SITE_NAME
  return {
    openGraph: {
      type: 'website',
      siteName: SITE_NAME,
      title: heading,
      description,
      url,
      images: [{ url: image, width: 1200, height: 630, alt: heading }],
    },
    twitter: {
      card: 'summary_large_image',
      title: heading,
      description,
      images: [image],
    },
  }
}

// Changelog version pages get their own release card. Path segments look like
// ['updates','changelog','v3-2-5']; the card is /changelog/<slug>.png.
export function changelogImageFor(segments) {
  if (!Array.isArray(segments) || segments.length < 2) return null
  const last = segments[segments.length - 1]
  const parent = segments[segments.length - 2]
  if (parent !== 'changelog') return null
  if (!/^v\d/.test(last)) return null // skip index/unreleased — no version card
  return abs(`/changelog/${last}.png`)
}
