export default {
  index: 'Overview',
  mdt: 'Using the MDT',
  'mdt-toolbar': 'MDT Toolbar & Status',
  statuses: 'Status Labels',
  'mdt-incidents': 'Working with Incidents',
  'mdt-query': 'Query: People & Plates',
  bolo: 'BOLO',
  'citations-charges': 'Citations & Charges',
  'officer-stats': 'My Activity',
  alpr: 'ALPR Plate Reader',
  'dispatch-console': 'Dispatch Console',
  'lasd-cad': 'LASD CAD / PCMS',
  'retro-mdt': '9100-T Retro Terminal',
  'pennsylvania-cad': 'Pennsylvania CAD',
  'in-car-screen': 'In-Car Screen',
  'leo-field-tools': 'LEO Field Tools',
  phone: 'Phone',
  'admin-panel': 'Staff Panel',
  replay: "Replay & Director's Cut",
  'bug-reports': 'Bug Reports',
  'civilian-vehicles': 'Civilian & Vehicles',
  playerlist: 'Player List',
}
